# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46e625a647e022b337912f5fcbf39790cc69a9c66b14ffc37a6b59a275e3523b6060b9c287479722501fedd6514cf37adf5d7e85f9e6c4d41ef32e895c414568

test:
  secret_key_base: dec6883a9e419d6cf6c05627bea410ff19ccd8ef0d30f54cba4d9c38febd4bfed6060cd7cadfca2b6affb8e91f1da07590c48387988f4d6481bf468e26996aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
